version: "3.8"
services:
  mern-client:
    stdin_open: true
    tty: true
    restart: always
    image: "dimasyudha/mern-client-${ENV}:${APP_VERSION}"
    container_name: mern-client
    ports:
      - "3000:${DOCKER_PORT}"
    env_file:
      - .env
