/*
TO-DO LISTS
 1. Add info in each stage
 2. How if branch contains numbers?
*/

pipeline {
    agent any
    tools {
        nodejs('nodejs-16')
    }
    options {
        parallelsAlwaysFailFast()
    }
    environment {
        BRANCH_NAME = "${params.BRANCH}"
        VM_IP = "${BRANCH_NAME == 'sit' ?  '58.236.169.3' : BRANCH_NAME == 'uat' ? '154.226.218.75' : BRANCH_NAME == 'prod' ? '196.172.27.77' : '123.163.194.154'}"
        VM_PORT = "${BRANCH_NAME == 'sit' ? '58' : BRANCH_NAME == 'uat' ? '154' : BRANCH_NAME == 'prod' ? '196' : '123'}"
        VM_USER = "${BRANCH_NAME == 'sit' ? 'dimas' : BRANCH_NAME == 'uat' ? 'yudha' : BRANCH_NAME == 'prod' ? 'pratama' : 'root'}"
        VM_ROOT_PATH = "${VM_USER == 'root' ? '/root' : '/home/${VM_USER}'}"
        VM_PASS = credentials('vm-pass')
        BOT_TOKEN = credentials('bot-token')
        GROUP_ID = credentials('group-id')
        APP_VERSION = "${sh(script: 'jq -r .version package.json', returnStdout: true).trim()}"
    }
    stages {
        stage('Variable') {
            steps {
                script {
                    BOT_TOKEN = "${BOT_TOKEN}"
                    GROUP_ID = "${GROUP_ID}"
                    RESULT = ""
                    TOOK = ""
                    USER = "${currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]['userId']}"
                    JOB = "${currentBuild.projectName}"
                    ENV = "${BRANCH_NAME}"
                    CONSOLE = "${BUILD_URL}/console"
                }
            }
        }
        stage('Environment') {
            steps {
                sh "cp -rf .env.${BRANCH_NAME} .env"
            }
        }
        stage('') {
            parallel {
                stage('Directory') {
                    steps {
                        sh "sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} mkdir -p ${VM_ROOT_PATH}/mern/client"
                    }
                }
                stage('Transfer') {
                    steps {
                        sh "sshpass -p '${VM_PASS}' scp -P ${VM_PORT} .env docker-compose.yml ${VM_USER}@${VM_IP}:${VM_ROOT_PATH}/mern/client"
                    }
                }
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    if (BRANCH_NAME == 'dev' || BRANCH_NAME == 'sit') {
                        sh "docker build --target node --build-arg ENV=${BRANCH_NAME} -t dimasyudha/mern-client-${BRANCH_NAME}:${APP_VERSION} ."
                    } else {
                        sh "docker build --target nginx --build-arg ENV=${BRANCH_NAME} -t dimasyudha/mern-client-${BRANCH_NAME}:${APP_VERSION} ."
                    }
                }
            }
        }
        stage('Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
                        docker login -u ${NEXUS_USER} -p ${NEXUS_PASS}
                    """
                }
            }
        }
        stage('Push') {
            steps {
                sh "docker push dimasyudha/mern-client-${BRANCH_NAME}:${APP_VERSION}"
            }
        }
        stage('Pull') {
            steps {
                sh "sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker-compose -f ${VM_ROOT_PATH}/mern/client/docker-compose.yml pull"
            }
        }
        stage('Destroy') {
            steps {
                sh "sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker-compose -f ${VM_ROOT_PATH}/mern/client/docker-compose.yml down"
            }
        }
        stage('Run') {
            steps {
                sh "sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker-compose -f ${VM_ROOT_PATH}/mern/client/docker-compose.yml up -d"
            }

        }
    }
    post {
        always {
            cleanWs()
            dir("${env.WORKSPACE}@tmp") {
                deleteDir()
            }
            dir("${env.WORKSPACE}@script") {
                deleteDir()
            }
            dir("${env.WORKSPACE}@script@tmp") {
                deleteDir()
            }
            sh """
                docker image prune -f
                sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker image prune -f
                curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage -d chat_id=${GROUP_ID} -d 'parse_mode=HTML' -d text='Result: ${RESULT}\nTook: ${TOOK}\nUser: ${USER}\nJob: ${JOB}\nEnv: ${ENV}\nConsole: ${CONSOLE}'
            """
        }
    }
}
