version: "3.8"
services:
  mern-service:
    stdin_open: true
    tty: true
    image: "dimasyudha.com/mern-service-${ENV}"
    container_name: "mern-service-${ENV}"
    ports:
      - "3001:3001"
    env_file:
      - .env