/*
TO-DO LISTS
 1. Add info in each stage
 2. How if branch contains numbers?
*/

pipeline {
    agent any
    tools {
        nodejs('nodejs-16')
    }
    environment {
        GIT_BRANCH = "${params.BRANCH}"
        VM_IP = "${GIT_BRANCH == 'dev' ? '123.163.194.154' : GIT_BRANCH == 'sit' ?  '58.236.169.3' : GIT_BRANCH == 'uat' ? '154.226.218.75' : GIT_BRANCH == 'prod' && '196.172.27.77'}"
        VM_PORT = "${GIT_BRANCH == 'dev' ? '123' : GIT_BRANCH == 'sit' ? '58' : GIT_BRANCH == 'uat' ? '154' : GIT_BRANCH == 'prod' && '196'}"
        VM_USER = "${GIT_BRANCH == 'dev' ? 'dimas' : GIT_BRANCH == 'sit' ? 'yudha' : GIT_BRANCH == 'uat' ? 'pratama' : GIT_BRANCH == 'prod' && 'dimasyudha'}"
        VM_PASS = credentials('vm-pass')
        BOT_TOKEN = credentials('bot-token')
        GROUP_ID = credentials('group-id')
    }
    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'dev', name: 'BRANCH', type: 'PT_BRANCH'
    }
    stages {
        stage('Save Variable Value') {
            steps {
                script {
                    BOT_TOKEN = "${BOT_TOKEN}"
                    GROUP_ID = "${GROUP_ID}"
                }
            }
        }
        stage('Initialize Directory') {
            steps {
                sh """
                    sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} mkdir -p /home/${VM_USER}/mern
                    sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} mkdir -p /home/${VM_USER}/mern/server
                """
            }
        }
        stage('Set Environment') {
            steps {
                sh """
                    cp -rf .env.${GIT_BRANCH} .env
                    sshpass -p '${VM_PASS}' scp -P ${VM_PORT} .env ${VM_USER}@${VM_IP}:/home/${VM_USER}/mern/server
                """
            }
        }
        stage('Docker Build') {
            steps {
                sh "docker build -t dimasyudha.com/mern-server-${GIT_BRANCH} ."
            }
        }
        stage('Login to Nexus') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-credentials', usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                    sh """
                        sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker login -u ${NEXUS_USER} -p ${NEXUS_PASS} dimasyudha.com
                        docker login -u ${NEXUS_USER} -p ${NEXUS_PASS} dimasyudha.com
                    """
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                sh "docker push dimasyudha.com/mern-server-${GIT_BRANCH}"
            }
        }
        stage('Docker Compose') {
            steps {
                sh """
                    sshpass -p '${VM_PASS}' scp -P ${VM_PORT} server/docker-compose.yml ${VM_USER}@${VM_IP}:/home/${VM_USER}/mern/server
                    sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker-compose -f /home/${VM_USER}/mern/server/docker-compose.yml down
                    sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker-compose -f /home/${VM_USER}/mern/server/docker-compose.yml pull
                    sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker-compose -f /home/${VM_USER}/mern/server/docker-compose.yml up -d
                """
            }
        }
    }
    post {
        always {
            sh """
                docker image prune -f
                sshpass -p '${VM_PASS}' ssh -o StrictHostKeyChecking=no ${VM_USER}@${VM_IP} -p ${VM_PORT} docker image prune -f
            """
        }
        success {
            sh "curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage -d chat_id=${GROUP_ID} -d 'parse_mode=HTML' -d text='Result: Success\nTook: ${currentBuild.durationString}\nUser: ${currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]['userId']}\nJob: ${currentBuild.projectName}\nEnv: ${GIT_BRANCH}\nConsole: ${BUILD_URL}console'"
        }
        failure {
            sh "curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage -d chat_id=${GROUP_ID} -d 'parse_mode=HTML' -d text='Result: Failure\nTook: ${currentBuild.durationString}\nUser: ${currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]['userId']}\nJob: ${currentBuild.projectName}\nEnv: ${GIT_BRANCH}\nConsole: ${BUILD_URL}console'"
        }
}
